### ISSUE TITLE
Bitfinex USD pricing

### ISSUE THREAD

**Issue by ghost** [Samourai-Wallet/Sentinel-iOS#1]
Pricing in USD on the main transactions list displays the correct amount when Bitfinex is selected, but when clicking the specific transactions it shows different/incorrect amount, looks like its using localbitcoins as source for all

**Comment by ghost** [comment]
Maybe easiest fix is to remove fiat? ;)

**Comment by euwars** [comment]
Fixed. 331720c06fc8db7c398c38459906021b7f7c6f33
